# Generated by Django 5.0 on 2024-01-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
